import "./globals.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from 'react-hot-toast';

import { ThemeProvider } from "@/providers/theme-provider";
import { ReduxProvider } from "@/providers/redux-provider";
import { ModalProvider } from "@/providers/modal-provider";
import { cn } from "@/lib/utils";

const font = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "sisCord - Discord clone",
	description: "Generated by create next app"
};

export default function RootLayout({
																		 children
																	 }: {
	children: React.ReactNode;
}) {
	return (
		<ReduxProvider>
			<ClerkProvider>
				<html lang="en" suppressHydrationWarning>
				<body className={cn(
					font.className,
					"bg-white dark:bg-[#313338]"
				)}>
				<ThemeProvider
					attribute="class"
					defaultTheme="dark"
					enableSystem={false}
					storageKey="theme"
				>
					{children}
					<ModalProvider/>
					<Toaster />
				</ThemeProvider>
				</body>
				</html>
			</ClerkProvider>
		</ReduxProvider>
	);
}
